name 'ssh-simple'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ssh-simple'
long_description 'Installs/Configures ssh-simple'
version '0.1.0'
